"""
Flask app using PyTorch - Compatible with Python 3.14
PRIMARY focus on image analysis (95%), clinical features are secondary (5%)
"""

from flask import Flask, render_template, request, send_file
import torch
import torch.nn as nn
from torchvision import transforms, models
from PIL import Image
import numpy as np
from fpdf import FPDF
import os
from datetime import datetime
from werkzeug.utils import secure_filename
import json

app = Flask(__name__)

# Configuration
UPLOAD_FOLDER = "uploads"
REPORT_FOLDER = "reports"
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg'}
IMG_SIZE = 224

os.makedirs(UPLOAD_FOLDER, exist_ok=True)
os.makedirs(REPORT_FOLDER, exist_ok=True)

app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
app.config['MAX_CONTENT_LENGTH'] = 16 * 1024 * 1024

# Device configuration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Define model architecture (same as training)
class CervicalCancerModel(nn.Module):
    def __init__(self):
        super(CervicalCancerModel, self).__init__()
        self.mobilenet = models.mobilenet_v2(weights=None)
        in_features = self.mobilenet.classifier[1].in_features
        self.mobilenet.classifier = nn.Sequential(
            nn.Dropout(0.5),
            nn.Linear(in_features, 128),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(64, 1),
            nn.Sigmoid()
        )
    
    def forward(self, x):
        return self.mobilenet(x)

# Load model
model = CervicalCancerModel().to(device)
try:
    model.load_state_dict(torch.load('cervical_cancer_pytorch_model.pth', map_location=device, weights_only=True))
    model.eval()
    print("✅ Model loaded successfully!")
except Exception as e:
    print(f"⚠️ Warning: Could not load model - {e}")
    print("Run train_pytorch_model.py first!")

# Load class indices
try:
    with open('class_indices.json', 'r') as f:
        class_to_idx = json.load(f)
    idx_to_class = {v: k for k, v in class_to_idx.items()}
    print(f"Class mapping: {class_to_idx}")
except:
    print("⚠️ Warning: class_indices.json not found, using defaults")
    class_to_idx = {'abnormal': 0, 'normal': 1}
    idx_to_class = {0: 'abnormal', 1: 'normal'}

# Image preprocessing
transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                        std=[0.229, 0.224, 0.225])
])

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

def preprocess_image(img_path):
    """Preprocess image for model prediction"""
    img = Image.open(img_path).convert('RGB')
    img_tensor = transform(img).unsqueeze(0)
    return img_tensor.to(device)

class MedicalReport(FPDF):
    def header(self):
        self.set_fill_color(173, 20, 87) 
        self.rect(0, 0, 210, 45, 'F') 
        
        self.set_font('Arial', 'B', 30)
        self.set_text_color(255, 255, 255)
        self.set_xy(0, 15)
        self.cell(210, 10, 'CANCER DIAGNOSTICS', 0, 1, 'C')
        
        self.set_font('Arial', '', 12)
        self.cell(210, 10, 'AI-Powered Cervical Screening Report', 0, 1, 'C')
        self.ln(20)

    def footer(self):
        self.set_y(-20)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 5, 'Disclaimer: This report is generated by an AI system.', 0, 1, 'C')
        self.cell(0, 5, 'Always consult with a healthcare professional for diagnosis.', 0, 1, 'C')

@app.route("/")
def home():
    return render_template("index.html")

@app.route("/predict", methods=["POST"])
def predict():
    # Validate image upload
    if 'pap_image' not in request.files:
        return "No file uploaded", 400
    
    file = request.files['pap_image']
    
    if file.filename == '':
        return "No file selected", 400
    
    if not allowed_file(file.filename):
        return "Invalid file type. Only PNG, JPG, JPEG allowed.", 400
    
    # Get all form data (clinical features)
    name = request.form.get("name", "Unknown Patient")
    age = int(request.form.get("age", 0))
    preg = int(request.form.get("preg", 0))
    smokes = int(request.form.get("smokes", 0))
    hpv = int(request.form.get("hpv", 0))
    pap = int(request.form.get("pap", 0))
    
    # Save uploaded image
    filename = secure_filename(file.filename)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    unique_filename = f"{timestamp}_{filename}"
    filepath = os.path.join(app.config['UPLOAD_FOLDER'], unique_filename)
    file.save(filepath)
    
    # === PRIMARY PREDICTION: IMAGE ANALYSIS ===
    img_tensor = preprocess_image(filepath)
    
    with torch.no_grad():
        prediction = model(img_tensor)
        raw_prob = float(prediction.squeeze().cpu().numpy())
    
    print(f"Raw model output: {raw_prob:.4f}")
    print(f"Class indices: {class_to_idx}")
    
    # Interpret based on class mapping
    # If 'abnormal' is class 0, then LOW probability = abnormal
    # If 'abnormal' is class 1, then HIGH probability = abnormal
    
    if class_to_idx.get('abnormal', 0) == 0:
        # abnormal is class 0, so LOW prob means abnormal
        abnormal_prob = (1 - raw_prob) * 100
    else:
        # abnormal is class 1, so HIGH prob means abnormal
        abnormal_prob = raw_prob * 100
    
    print(f"Abnormal probability: {abnormal_prob:.2f}%")
    
    # Calculate minor clinical risk adjustment (only 5% influence)
    clinical_risk = 0
    if age > 45: clinical_risk += 2
    if preg > 3: clinical_risk += 2
    if smokes == 1: clinical_risk += 3
    if hpv == 1: clinical_risk += 5
    if pap == 1: clinical_risk += 5
    
    # Combine: 95% image, 5% clinical
    combined_prob = (abnormal_prob * 0.95) + (clinical_risk * 0.5)
    
    print(f"Clinical risk: {clinical_risk}")
    print(f"Combined probability: {combined_prob:.2f}%")
    
    # Determine result - anything above 70% is HIGH RISK
    if combined_prob >= 50:
        result_text = "HIGH RISK DETECTED"
        color_class = "high"
        text_color = (200, 0, 0)
        bg_color = (255, 235, 238)
        recommendation = "URGENT: Immediate consultation with oncologist recommended. Further diagnostic tests required."
    elif combined_prob >= 40:
        result_text = "MODERATE RISK DETECTED"
        color_class = "medium"
        text_color = (255, 140, 0)
        bg_color = (255, 248, 220)
        recommendation = "Follow-up recommended. Schedule appointment with gynecologist for detailed examination."
    else:
        result_text = "LOW RISK DETECTED"
        color_class = "low"
        text_color = (0, 128, 0)
        bg_color = (232, 245, 233)
        recommendation = "Results appear within normal range. Continue regular screening as per schedule."
    
    # Generate PDF Report
    pdf = MedicalReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Patient Info
    pdf.set_y(55)
    pdf.set_font("Arial", "B", 14)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(0, 10, "Patient Information", ln=True)
    
    pdf.set_fill_color(248, 249, 250)
    pdf.set_draw_color(220, 220, 220)
    pdf.rect(10, 65, 190, 55, 'FD')
    
    pdf.set_font("Arial", "", 12)
    pdf.set_xy(15, 70)
    pdf.cell(90, 8, f"Patient Name: {name}", ln=0)
    pdf.cell(90, 8, f"Age: {age} Years", ln=1)
    
    pdf.set_x(15)
    pdf.cell(90, 8, f"Pregnancies: {preg}", ln=0)
    pdf.cell(90, 8, f"Smoker: {'Yes' if smokes==1 else 'No'}", ln=1)

    pdf.set_x(15)
    pdf.cell(90, 8, f"HPV Result: {'Positive' if hpv==1 else 'Negative'}", ln=0)
    pdf.cell(90, 8, f"Pap Smear: {'Abnormal' if pap==1 else 'Normal'}", ln=1)
    
    pdf.set_x(15)
    pdf.cell(90, 8, f"Test Date: {datetime.now().strftime('%B %d, %Y')}", ln=0)
    pdf.cell(90, 8, f"Analysis Method: AI Image", ln=1)

    # Result Box
    pdf.ln(20)
    box_start_y = pdf.get_y()
    
    pdf.set_fill_color(*bg_color)
    pdf.set_draw_color(*text_color)
    pdf.rect(10, box_start_y, 190, 75, 'FD')
    
    pdf.set_y(box_start_y + 5)
    pdf.set_font("Arial", "B", 18)
    pdf.set_text_color(*text_color)
    pdf.cell(0, 10, result_text, align='C', ln=True)
    
    pdf.set_font("Arial", "", 11)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 8, "Based on Neural Network Image Analysis", align='C', ln=True)

    pdf.ln(2)
    pdf.set_font("Arial", "B", 14)
    pdf.set_text_color(*text_color)
    pdf.cell(0, 8, f"Risk Score: {combined_prob:.1f}%", align='C', ln=True)
    
    pdf.set_font("Arial", "", 9)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, f"(Image Analysis: {abnormal_prob:.1f}% | Clinical Factors: +{clinical_risk})", align='C', ln=True)
    
    # Risk Bar
    bar_y = pdf.get_y() + 5
    bar_width = 140
    bar_height = 10
    start_x = (210 - bar_width) / 2
    
    # Background
    pdf.set_fill_color(220, 220, 220)
    pdf.rect(start_x, bar_y, bar_width, bar_height, 'F')
    
    # Filled portion
    fill_width = (min(combined_prob, 100) / 100) * bar_width
    pdf.set_fill_color(*text_color)
    pdf.rect(start_x, bar_y, fill_width, bar_height, 'F')
    
    # Recommendation
    pdf.set_y(bar_y + 18)
    pdf.set_font("Arial", "B", 11)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(0, 8, "Medical Recommendation:", align='C', ln=True)
    pdf.set_font("Arial", "", 10)
    pdf.multi_cell(0, 6, recommendation, align='C')

    # Quote
    pdf.set_y(box_start_y + 100)
    pdf.set_font("Times", "I", 14)
    pdf.set_text_color(173, 20, 87)
    pdf.cell(0, 10, '"Early detection saves lives."', align='C', ln=True)

    # Save PDF
    pdf_filename = f"{name.replace(' ', '_')}_Report.pdf"
    pdf_filepath = os.path.join(REPORT_FOLDER, pdf_filename)
    pdf.output(pdf_filepath)

    return render_template("result.html",
                           name=name,
                           result=result_text,
                           prob=round(combined_prob, 1),
                           color=color_class,
                           file=pdf_filename,
                           recommendation=recommendation)

@app.route("/download/<filename>")
def download(filename):
    return send_file(os.path.join(REPORT_FOLDER, filename), as_attachment=True)

if __name__ == "__main__":
    app.run(debug=True)